---
- name: ssl dependencies
  yum: name=openssl-libs state=present
  when: ansible_distribution_major_version|int > 6
  tags:
    - ssl
    - packages

- name: ssl dependencies for centos 6
  yum: name=openssl state=present
  when: ansible_distribution_major_version|int < 7
  tags:
    - ssl
    - packages

- name: install private keys
  copy: content="{{ item.value.private_key }}" dest="/etc/pki/tls/private/{{ item.key }}.key" owner=root group=root mode=0600
  with_dict: ssl_certificates
  when: ssl_certificates|length > 0 and item.value.private_key is defined
  no_log: true
  tags:
    - ssl
    - configuration

- name: install certificates
  copy: content="{{ item.value.certificate }}" dest="/etc/pki/tls/certs/{{ item.key }}.crt" owner=root group=root mode=0644
  with_dict: ssl_certificates
  when: ssl_certificates|length > 0 and item.value.certificate is defined
  no_log: true
  tags:
    - ssl
    - configuration

- name: install certificate chains
  template: src=chain.pem.j2 dest="/etc/pki/tls/certs/{{ item.key }}.chain.crt" owner=root group=root mode=0644
  with_dict: ssl_certificates
  when: ssl_certificates|length > 0 and item.value.chain is defined
  no_log: true
  tags:
    - ssl
    - configuration

- name: install certificate bundle
  template: src=bundle.pem.j2 dest="/etc/pki/tls/certs/{{ item.key }}.bundle.crt" owner=root group=root mode=0644
  with_dict: ssl_certificates
  when: ssl_certificates|length > 0 and item.value.certificate is defined
  no_log: true
  tags:
    - ssl
    - configuration

- name: install complete bundle
  template: src=complete.pem.j2 dest="/etc/pki/tls/certs/{{ item.key }}.pem" owner=root group=root mode=0600
  with_dict: ssl_certificates
  when: ssl_certificates|length > 0 and item.value.certificate is defined
  no_log: true
  tags:
    - ssl
    - configuration
